webtalk_init -webtalk_dir C:/Users/dilsh/LAB10_Dilshan_New/LAB10/LAB10.sim/TB_Decoder_3_to_8/behav/xsim/xsim.dir/TB_Decoder_3_to_8_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Jul 25 22:50:26 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "42d18b2525b056b7b3ef00b7402b363d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f330702f431647419194c50ab3747a93" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2112 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6964_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3153998198 -regid "" -xml C:/Users/dilsh/LAB10_Dilshan_New/LAB10/LAB10.sim/TB_Decoder_3_to_8/behav/xsim/xsim.dir/TB_Decoder_3_to_8_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/dilsh/LAB10_Dilshan_New/LAB10/LAB10.sim/TB_Decoder_3_to_8/behav/xsim/xsim.dir/TB_Decoder_3_to_8_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/dilsh/LAB10_Dilshan_New/LAB10/LAB10.sim/TB_Decoder_3_to_8/behav/xsim/xsim.dir/TB_Decoder_3_to_8_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
